array_width          = 95
attr_fn_like_width   = 120
chain_width          = 120
combine_control_expr = false
comment_width        = 120
edition              = "2021"
max_width            = 120
merge_imports        = true
reorder_imports      = true
use_small_heuristics = "Max"
